export default{
    home:require('../assets/images/home2.png'),
    gradientCircleBg: require('../assets/images/gradientCircle.png'),
    c_Letter: require('../assets/images/C_Letter.png'),
    appleIcon: require('../assets/images/appleIcon.png'),
    darkappleIcon: require('../assets/images/appleblack.png'),
    googleIcon: require('../assets/images/googleIcon.png'),
    facebookIcon: require('../assets/images/facebookIcon.png'),
    backArrow: require('../assets/images/backarrow.png'),
    translate: require('../assets/images/translate.png'),
    user:require('../assets/images/User.png'),
    message:require('../assets/images/Message.png'),
    search:require('../assets/images/Search.png'),
    send:require('../assets/images/send.png'),
    status:require('../assets/images/status.jpg'),
}